#!python3
'''
This module acts as a tool to reference Salesforce fields
in the Account object. Doing it this way allows other
instances of the alumni database to use these Python
tools, even if they have slightly different field names.
(In other words, this file can be edited to run later.)
'''
Id = 'Id'
IsDeleted = 'IsDeleted'
MasterRecordId = 'MasterRecordId'
Name = 'Name'
Type = 'Type'
RecordTypeId = 'RecordTypeId'
ParentId = 'ParentId'
BillingStreet = 'BillingStreet'
BillingCity = 'BillingCity'
BillingState = 'BillingState'
BillingPostalCode = 'BillingPostalCode'
BillingCountry = 'BillingCountry'
BillingLatitude = 'BillingLatitude'
BillingLongitude = 'BillingLongitude'
ShippingStreet = 'ShippingStreet'
ShippingCity = 'ShippingCity'
ShippingState = 'ShippingState'
ShippingPostalCode = 'ShippingPostalCode'
ShippingCountry = 'ShippingCountry'
ShippingLatitude = 'ShippingLatitude'
ShippingLongitude = 'ShippingLongitude'
Phone = 'Phone'
Fax = 'Fax'
Website = 'Website'
Industry = 'Industry'
AnnualRevenue = 'AnnualRevenue'
NumberOfEmployees = 'NumberOfEmployees'
Description = 'Description'
OwnerId = 'OwnerId'
CreatedDate = 'CreatedDate'
CreatedById = 'CreatedById'
LastModifiedDate = 'LastModifiedDate'
LastModifiedById = 'LastModifiedById'
SystemModstamp = 'SystemModstamp'
LastActivityDate = 'LastActivityDate'
LastViewedDate = 'LastViewedDate'
LastReferencedDate = 'LastReferencedDate'
Jigsaw = 'Jigsaw'
JigsawCompanyId = 'JigsawCompanyId'
AccountSource = 'AccountSource'
SicDesc = 'SicDesc'
Principal__c = 'Principal__c'
Alternate_Names__c = 'Alternate_Names__c'
CEEB_Code__c = 'CEEB_Code__c'
College_Navigator_Link__c = 'College_Navigator_Link__c'
Distance_from_Chicago__c = 'Distance_from_Chicago__c'
HBCU__c = 'HBCU__c'
NCESid__c = 'NCESid__c'
X1st_year_retention_rate__c = 'X1st_year_retention_rate__c'
X6_yr_completion_rate__c = 'X6_yr_completion_rate__c'
X6_yr_minority_completion_rate__c = 'X6_yr_minority_completion_rate__c'
X6_yr_transfer_rate__c = 'X6_yr_transfer_rate__c'
X6_yr_minority_transfer_rate__c = 'X6_yr_minority_transfer_rate__c'
College_Type__c = 'College_Type__c'
rollupAttendingC__c = 'rollupAttendingC__c'
of_GraduatesC__c = 'of_GraduatesC__c'
planning_to_MatriculateC__c = 'planning_to_MatriculateC__c'
Transferred_WithdrewC__c = 'Transferred_WithdrewC__c'
