#!python3
'''
Namespace for column headers of NSC file
This file "future proofs" raw detail reports by making a single
reference to the table headers in the reports
'''
YOUR_UNIQUE_IDENTIFIER = "YOUR_UNIQUE_IDENTIFIER"
FIRST_NAME = "FIRST_NAME"
MIDDLE_NAME = "MIDDLE_NAME"
LAST_NAME = "LAST_NAME"
NAME_SUFFIX = "NAME_SUFFIX"
REQUESTER_RETURN_FIELD = "REQUESTER_RETURN_FIELD"
RECORD_FOUND_Y_N = "RECORD_FOUND_Y/N"
HIGH_SCHOOL_CODE = "HIGH_SCHOOL_CODE"
HIGH_SCHOOL_GRAD_DATE = "HIGH_SCHOOL_GRAD_DATE"
COLLEGE_CODE_BRANCH = "COLLEGE_CODE/BRANCH"
COLLEGE_NAME = "COLLEGE_NAME"
COLLEGE_STATE = "COLLEGE_STATE"
TWO_YEAR_4_YEAR = "2-YEAR/4-YEAR"
PUBLIC_PRIVATE = "PUBLIC/PRIVATE"
ENROLLMENT_BEGIN = "ENROLLMENT_BEGIN"
ENROLLMENT_END = "ENROLLMENT_END"
ENROLLMENT_STATUS = "ENROLLMENT_STATUS"
GRADUATED = "GRADUATED"
GRADUATION_DATE = "GRADUATION_DATE"
DEGREE_TITLE = "DEGREE_TITLE"
MAJOR = "MAJOR"
COLLEGE_SEQUENCE = "COLLEGE_SEQUENCE"
PROGRAM_CODE = "PROGRAM_CODE"

